# Generated by cucumber-sinatra. (2015-08-25 14:54:07 +0100)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'app/noughts_and_crosses.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = NoughtsAndCrosses

class NoughtsAndCrossesWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  NoughtsAndCrossesWorld.new
end
